import { ReactNode } from "react";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "@@@Elice Account",
  description: "Generated by create next app",
};

export default async function signup({ children }: { children: ReactNode }) {
  return (
    <html>
      <body>{children}</body>
    </html>
  );
}
